import re
from pathlib import Path

import pytest

import jj_stack.ui as ui
from jj_stack.cli import _find_subcommand_parser, build_parser, main
from jj_stack.cli_help import _command_usage_message
from jj_stack.commands.view import ViewSelector
from jj_stack.errors import EXIT_USAGE, CliError
from tests.support.output_assertions import assert_output_contains


def test_main_reports_missing_repo_without_traceback(
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
) -> None:
    repo = tmp_path / "missing-repo"

    exit_code = main(["--repository", str(repo), "submit"])
    captured = capsys.readouterr()

    assert exit_code == 1
    assert str(repo) in captured.err
    assert "does not exist" in captured.err
    assert "Traceback" not in captured.err


def test_main_reports_non_jj_directory_without_traceback(
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
) -> None:
    plain_dir = tmp_path / "not-a-jj-repo"
    plain_dir.mkdir()

    exit_code = main(["--repository", str(plain_dir), "submit"])
    captured = capsys.readouterr()

    assert exit_code == 1
    assert "Not inside a jj workspace" in captured.err
    assert "Traceback" not in captured.err


def test_main_renders_semantic_cli_errors_without_flattening_first(
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    def fake_view(**kwargs) -> int:
        raise CliError(("Problem at ", ui.change_id("abcdefgh1234")))

    monkeypatch.setattr("jj_stack.cli.view_command.view", fake_view)

    exit_code = main(["view"])
    captured = capsys.readouterr()

    assert exit_code == 1
    assert "Error: Problem at abcdefgh" in captured.err


def test_cleanup_close_requires_pr_selection(capsys) -> None:
    exit_code = main(["cleanup", "--close"])
    captured = capsys.readouterr()

    assert exit_code == EXIT_USAGE
    assert "cleanup --close requires --pull-request" in captured.err


def test_command_usage_preserves_semantics_without_ansi(monkeypatch) -> None:
    monkeypatch.setenv("PYTHON_COLORS", "1")
    parser = _find_subcommand_parser(build_parser(), "relink")
    assert parser is not None

    message = _command_usage_message(parser)

    assert "\x1b" not in ui.plain_text(message)
    assert isinstance(message, tuple)
    labels = {part.text: part.labels for part in message if isinstance(part, ui.SemanticText)}
    for token, label in (
        ("jj-stack relink", "command"),
        ("--repository", "option"),
        ("REPO", "metavar"),
        ("REVSET", "metavar"),
    ):
        assert label in labels[token]


def test_help_website_reference_marks_cli_tokens_for_styling(monkeypatch, capsys) -> None:
    monkeypatch.setenv("PYTHON_COLORS", "1")

    exit_code = main(["help", "--website-reference"])
    captured = capsys.readouterr()

    assert exit_code == 0
    assert "\x1b" not in captured.out
    for class_name in ("cli-command", "cli-option", "cli-metavar"):
        assert f'class="{class_name}"' in captured.out

    unmarked = re.sub(r"<code\b[^>]*>.*?</code>", "", captured.out, flags=re.DOTALL)
    unmarked = re.sub(r"<span\b[^>]*>.*?</span>", "", unmarked, flags=re.DOTALL)
    assert re.search(r"(?<![\w-])--[a-z]", unmarked) is None
    assert re.search(r'<code class="cli-inline">@-?</code>', captured.out) is None
    assert re.search(r'<code class="cli-inline">[^<]*--', captured.out) is None


def test_help_all_keeps_terminal_top_level_contract(capsys) -> None:
    exit_code = main(["help", "--all"])
    captured = capsys.readouterr()

    assert exit_code == 0
    assert_output_contains(captured.out, "Usage: jj-stack", "Advanced repair:")
    assert "Generated by jj-stack" not in captured.out
    assert "Usage: jj-stack submit" not in captured.out


def test_main_preserves_view_selector_order_and_end_of_options(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    observed: dict[str, object] = {}

    def fake_view(**kwargs) -> int:
        observed.update(kwargs)
        return 0

    monkeypatch.setattr("jj_stack.cli.view_command.view", fake_view)

    exit_code = main(
        ["view", "foo", "-vp17", "bar", "-vp", "18", "baz", "--", "--pull-request", "7"]
    )

    assert exit_code == 0
    assert observed["selectors"] == (
        ViewSelector(kind="revset", value="foo"),
        ViewSelector(kind="pr", value="17"),
        ViewSelector(kind="revset", value="bar"),
        ViewSelector(kind="pr", value="18"),
        ViewSelector(kind="revset", value="baz"),
        ViewSelector(kind="revset", value="--pull-request"),
        ViewSelector(kind="revset", value="7"),
    )
    assert observed["verbose"] is True


@pytest.mark.parametrize("argv", [["pants"], ["pants", "-h"], ["help", "pants"]])
def test_main_reports_unknown_command_with_short_recovery_hint(
    argv: list[str],
    capsys: pytest.CaptureFixture[str],
) -> None:
    exit_code = main(argv)
    captured = capsys.readouterr()

    assert exit_code == EXIT_USAGE
    assert_output_contains(captured.err, "Unknown command pants.")
    err_lines = captured.err.splitlines()
    assert err_lines[0] == "Error: Unknown command pants."
    assert "Hint: Run jj-stack help to list commands." in err_lines


def test_sync_rejects_incompatible_selectors_before_repo_access(
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
) -> None:
    exit_code = main(["--repository", str(tmp_path), "sync", "--all", "--pull-request", "17"])
    captured = capsys.readouterr()

    assert exit_code == EXIT_USAGE
    assert "Use only one of sync --all, --pull-request, or a revset" in captured.err
